Feature selection+payment
liviambrasil/drivent-front pull request #1
Opened 2021-09-03 15:25 UTC by liviambrasil

2021-09-03 15:32 UTC, mrcs22 approved these changes

2021-09-06 17:55 UTC, gugabs requested changes

2021-09-06 17:55 UTC, gugabs commented on src/pages/Dashboard/Payment/ChooseTickets.js
> +          </Selection>
Pensem que esse sistema deve funcionar para diversos eventos, isso quer dizer que vocês devem desenvolver a aplicação pensando na possibilidade da adição de novos tipos de ingressos e que informações como nome e preço devem vir do banco de dados.

2021-09-06 17:55 UTC, gugabs commented on src/pages/Dashboard/Payment/ChooseTickets.js
> +              </Selection>
O mesmo caso de dinamismo ocorre aqui.

2021-09-06 17:55 UTC, gugabs commented on src/pages/Dashboard/Payment/PaymentInfo.js
> +// `;
Cuidado com os resquícios de código perdidos.

2021-09-06 17:55 UTC, gugabs commented on src/pages/Dashboard/Payment/creditCard.js
> +export default class PaymentForm extends React.Component {
Esse componente está no modelo antigo do React, seria legal transportá-lo para o padrão moderno do mesmo de acordo com o front-end do projeto.

2021-09-08 21:24 UTC, gugabs requested changes

2021-09-08 21:24 UTC, gugabs commented on src/pages/Dashboard/Payment/PaymentInfo.js
> +>>>>>>> 0872e1f9311c768b7c635c0c62de32d15cc14560
Ficou uma sinalização de conflito do Git aqui.

2021-09-08 21:28 UTC, gugabs approved these changes

2021-09-08 21:33 UTC, merged